### ISSUE TITLE
Implement sophisticated parser other than dy upd

### ISSUE THREAD

**Issue by StoneDot** [awslabs/dynein#146]
Currently, only the `upd` command provides the sophisticated parser for input, which is implemented by #132. We should offer the same feature for the following commands;

- `dy put`
- `dy query` for `--sort-key`
- `dy bwrite`

```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/dynein/issues/162
- [ ] https://github.com/awslabs/dynein/issues/163
- [ ] https://github.com/awslabs/dynein/issues/164
```

**Comment by StoneDot** [comment]
We have completed all improvements. I am closing this.
